---
- name: Configure module for containerd
  shell:
    cmd: |
      tee /etc/modules-load.d/containerd.conf<<EOF
      overlay
      br_netfilter
      EOF

- name: Apply sysctl params without reboot
  command: sysctl --system

- name: Installing Prerequisites for Kubernetes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - vim
      - software-properties-common
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker
    update_cache: yes

- name: "Update cache & Full system update"
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true

- name: Install containerd.
  apt:
    name:
      - containerd.io
    state: present

- name: Configure containerd.
  file:
    path: /etc/containerd
    state: directory

- name: Remove disabled_plugins = ["cri"] entry from /etc/containerd/config.toml
  lineinfile:
    dest: /etc/containerd/config.toml
    regexp: disabled_plugins
    state: absent

- name: Enable containerd service, and start it.
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes
