---
- name: Remove packages
  include: remove-packages.yml
- name: Swap inactive
  include: swap-inactive.yml
- name: Installing Kubernetes Packages
  include: kubernetes-packages.yml
- name: Sysctl configure 
  include: sysctl-configure.yml
- name: Containerd install 
  include: containerd-install.yml
- name: Kubernetes init on Master
  include: kubernetes-init.yml
  when: "'master' in ansible_hostname"
- name: Calico install on Master
  include: calico-install.yml
  when: "'master' in ansible_hostname"
- name: Worker Configuration
  include: worker-configuration.yml
  when: "'node' in ansible_hostname"
