---
- name: Set hostname
  include_tasks: set-hostname.yml

- name: Set hosts
  include_tasks: set-hosts.yml

- name: Remove packages, apt update, reboot
  include_tasks: remove-packages.yml

- name: Swap inactive
  include_tasks: swap-inactive.yml

- name: Installing Kubernetes Packages
  include_tasks: kubernetes-packages.yml

- name: Sysctl configure 
  include_tasks: sysctl-configure.yml

- name: Containerd install 
  include_tasks: containerd-install.yml

- name: Kubernetes init on Control
  include_tasks: kubernetes-init.yml
  when: "'control' in ansible_hostname"

- name: Calico install on Control
  include_tasks: calico-install.yml
  when: "'control' in ansible_hostname"

- name: Worker init
  include_tasks: worker-init.yml
  when: "'worker' in ansible_hostname"


