---
- name: Remove packages
  include_tasks: remove-packages.yml
- name: Swap inactive
  include_tasks: swap-inactive.yml
- name: Installing Kubernetes Packages
  include_tasks: kubernetes-packages.yml
- name: Sysctl configure 
  include_tasks: sysctl-configure.yml
- name: Containerd install 
  include_tasks: containerd-installing.yml
- name: Kubernetes init on Master
  include_tasks: kubernetes-init.yml
  when: "'master' in ansible_hostname"
- name: Calico install on Master
  include_tasks: calico-install.yml
  when: "'master' in ansible_hostname"
- name: Worker init
  include_tasks: worker-init.yml
  when: "'node' in ansible_hostname"
